export const ALL_COUNTRIES = [
  { name: "Afeganistão", flag: "🇦🇫" }, { name: "África do Sul", flag: "🇿🇦" }, { name: "Albânia", flag: "🇦🇱" },
  { name: "Alemanha", flag: "🇩🇪" }, { name: "Andorra", flag: "🇦🇩" }, { name: "Angola", flag: "🇦🇴" },
  { name: "Anguila", flag: "🇦🇮" }, { name: "Antárctida", flag: "🇦🇶" }, { name: "Antígua e Barbuda", flag: "🇦🇬" },
  { name: "Arábia Saudita", flag: "🇸🇦" }, { name: "Argélia", flag: "🇩🇿" }, { name: "Argentina", flag: "🇦🇷" },
  { name: "Arménia", flag: "🇦🇲" }, { name: "Aruba", flag: "🇦🇼" }, { name: "Austrália", flag: "🇦🇺" },
  { name: "Áustria", flag: "🇦🇹" }, { name: "Azerbaijão", flag: "🇦🇿" }, { name: "Bahamas", flag: "🇧🇸" },
  { name: "Bahrein", flag: "🇧🇭" }, { name: "Bangladesh", flag: "🇧🇩" }, { name: "Barbados", flag: "🇧🇧" },
  { name: "Bélgica", flag: "🇧🇪" }, { name: "Belize", flag: "🇧🇿" }, { name: "Benin", flag: "🇧🇯" },
  { name: "Bermudas", flag: "🇧🇲" }, { name: "Bielorrússia", flag: "🇧🇾" }, { name: "Bolívia", flag: "🇧🇴" },
  { name: "Bósnia e Herzegovina", flag: "🇧🇦" }, { name: "Botswana", flag: "🇧🇼" }, { name: "Brasil", flag: "🇧🇷" },
  { name: "Bulgária", flag: "🇧🇬" }, { name: "Burkina Faso", flag: "🇧🇫" }, { name: "Burundi", flag: "🇧🇮" },
  { name: "Butão", flag: "🇧🇹" }, { name: "Cabo Verde", flag: "🇨🇻" }, { name: "Camarões", flag: "🇨🇲" },
  { name: "Camboja", flag: "🇰🇭" }, { name: "Canadá", flag: "🇨🇦" }, { name: "Catar", flag: "🇶🇦" },
  { name: "Cazaquistão", flag: "🇰🇿" }, { name: "Chade", flag: "🇹🇩" }, { name: "Chile", flag: "🇨🇱" },
  { name: "China", flag: "🇨🇳" }, { name: "Chipre", flag: "🇨🇾" }, { name: "Colômbia", flag: "🇨🇴" },
  { name: "Comores", flag: "🇰🇲" }, { name: "Congo", flag: "🇨🇬" }, { name: "Coreia do Sul", flag: "🇰🇷" },
  { name: "Costa do Marfim", flag: "🇨🇮" }, { name: "Costa Rica", flag: "🇨🇷" }, { name: "Croácia", flag: "🇭🇷" },
  { name: "Cuba", flag: "🇨🇺" }, { name: "Dinamarca", flag: "🇩🇰" }, { name: "Djibuti", flag: "🇩🇯" },
  { name: "Dominica", flag: "🇩🇲" }, { name: "Egito", flag: "🇪🇬" }, { name: "El Salvador", flag: "🇸🇻" },
  { name: "Emirados Árabes Unidos", flag: "🇦🇪" }, { name: "Equador", flag: "🇪🇨" }, { name: "Eritreia", flag: "🇪🇷" },
  { name: "Eslováquia", flag: "🇸🇰" }, { name: "Eslovénia", flag: "🇸🇮" }, { name: "Espanha", flag: "🇪🇸" },
  { name: "Estados Unidos", flag: "🇺🇸" }, { name: "Estónia", flag: "🇪🇪" }, { name: "Etiópia", flag: "🇪🇹" },
  { name: "Fiji", flag: "🇫🇯" }, { name: "Filipinas", flag: "🇵🇭" }, { name: "Finlândia", flag: "🇫🇮" },
  { name: "França", flag: "🇫🇷" }, { name: "Gabão", flag: "🇬🇦" }, { name: "Gâmbia", flag: "🇬🇲" },
  { name: "Gana", flag: "🇬🇭" }, { name: "Geórgia", flag: "🇬🇪" }, { name: "Granada", flag: "🇬🇩" },
  { name: "Grécia", flag: "🇬🇷" }, { name: "Guatemala", flag: "🇬🇹" }, { name: "Guiné", flag: "🇬🇳" },
  { name: "Guiné-Bissau", flag: "🇬🇼" }, { name: "Haiti", flag: "🇭🇹" }, { name: "Honduras", flag: "🇭🇳" },
  { name: "Hungria", flag: "🇭🇺" }, { name: "Iémen", flag: "🇾🇪" }, { name: "Ilhas Marshall", flag: "🇲🇭" },
  { name: "Ilhas Salomão", flag: "🇸🇧" }, { name: "Índia", flag: "🇮🇳" }, { name: "Indonésia", flag: "🇮🇩" },
  { name: "Irão", flag: "🇮🇷" }, { name: "Iraque", flag: "🇮🇶" }, { name: "Irlanda", flag: "🇮🇪" },
  { name: "Islândia", flag: "🇮🇸" }, { name: "Israel", flag: "🇮🇱" }, { name: "Itália", flag: "🇮🇹" },
  { name: "Jamaica", flag: "🇯🇲" }, { name: "Japão", flag: "🇯🇵" }, { name: "Jordânia", flag: "🇯🇴" },
  { name: "Kuwait", flag: "🇰🇼" }, { name: "Laos", flag: "🇱🇦" }, { name: "Lesoto", flag: "🇱🇸" },
  { name: "Letónia", flag: "🇱🇻" }, { name: "Líbano", flag: "🇱🇧" }, { name: "Libéria", flag: "🇱🇷" },
  { name: "Líbia", flag: "🇱🇾" }, { name: "Liechtenstein", flag: "🇱🇮" }, { name: "Lituânia", flag: "🇱🇹" },
  { name: "Luxemburgo", flag: "🇱🇺" }, { name: "Madagáscar", flag: "🇲🇬" }, { name: "Malásia", flag: "🇲🇾" },
  { name: "Malawi", flag: "🇲🇼" }, { name: "Maldivas", flag: "🇲🇻" }, { name: "Mali", flag: "🇲🇱" },
  { name: "Malta", flag: "🇲🇹" }, { name: "Marrocos", flag: "🇲🇦" }, { name: "Maurícia", flag: "🇲🇺" },
  { name: "Mauritânia", flag: "🇲🇷" }, { name: "México", flag: "🇲🇽" }, { name: "Moldávia", flag: "🇲🇩" },
  { name: "Mónaco", flag: "🇲🇨" }, { name: "Mongólia", flag: "🇲🇳" }, { name: "Montenegro", flag: "🇲🇪" },
  { name: "Namíbia", flag: "🇳🇦" }, { name: "Nauru", flag: "🇳🇷" }, { name: "Nepal", flag: "🇳🇵" },
  { name: "Nicarágua", flag: "🇳🇮" }, { name: "Níger", flag: "🇳🇪" }, { name: "Nigéria", flag: "🇳🇬" },
  { name: "Noruega", flag: "🇳🇴" }, { name: "Nova Zelândia", flag: "🇳🇿" }, { name: "Omã", flag: "🇴🇲" },
  { name: "Países Baixos", flag: "🇳🇱" }, { name: "Palau", flag: "🇵🇼" }, { name: "Panamá", flag: "🇵🇦" },
  { name: "Papua Nova Guiné", flag: "🇵🇬" }, { name: "Paquistão", flag: "🇵🇰" }, { name: "Paraguai", flag: "🇵🇾" },
  { name: "Peru", flag: "🇵🇪" }, { name: "Polónia", flag: "🇵🇱" }, { name: "Portugal", flag: "🇵🇹" },
  { name: "Quénia", flag: "🇰🇪" }, { name: "Quirguistão", flag: "🇰🇬" }, { name: "Reino Unido", flag: "🇬🇧" },
  { name: "República Centro-Africana", flag: "🇨🇫" }, { name: "República Checa", flag: "🇨🇿" }, { name: "República Dominicana", flag: "🇩🇴" },
  { name: "Roménia", flag: "🇷🇴" }, { name: "Ruanda", flag: "🇷🇼" }, { name: "Rússia", flag: "🇷🇺" },
  { name: "Samoa", flag: "🇼🇸" }, { name: "Santa Lúcia", flag: "🇱🇨" }, { name: "São Cristóvão e Neves", flag: "🇰🇳" },
  { name: "São Marino", flag: "🇸🇲" }, { name: "São Vicente e Granadinas", flag: "🇻🇨" }, { name: "Senegal", flag: "🇸🇳" },
  { name: "Sérvia", flag: "🇷🇸" }, { name: "Seychelles", flag: "🇸🇨" }, { name: "Serra Leoa", flag: "🇸🇱" },
  { name: "Singapura", flag: "🇸🇬" }, { name: "Síria", flag: "🇸🇾" }, { name: "Somália", flag: "🇸🇴" },
  { name: "Sri Lanka", flag: "🇱🇰" }, { name: "Suazilândia", flag: "🇸🇿" }, { name: "Sudão", flag: "🇸🇩" },
  { name: "Suécia", flag: "🇸🇪" }, { name: "Suíça", flag: "🇨🇭" }, { name: "Suriname", flag: "🇸🇷" },
  { name: "Tailândia", flag: "🇹🇭" }, { name: "Tajiquistão", flag: "🇹🇯" }, { name: "Tanzânia", flag: "🇹🇿" },
  { name: "Timor-Leste", flag: "🇹🇱" }, { name: "Togo", flag: "🇹🇬" }, { name: "Tonga", flag: "🇹🇴" },
  { name: "Trindade e Tobago", flag: "🇹🇹" }, { name: "Tunísia", flag: "🇹🇳" }, { name: "Turquemenistão", flag: "🇹🇲" },
  { name: "Turquia", flag: "🇹🇷" }, { name: "Tuvalu", flag: "🇹🇻" }, { name: "Ucrânia", flag: "🇺🇦" },
  { name: "Uganda", flag: "🇺🇬" }, { name: "Uruguai", flag: "🇺🇾" }, { name: "Uzbequistão", flag: "🇺🇿" },
  { name: "Vanuatu", flag: "🇻🇺" }, { name: "Vaticano", flag: "🇻🇦" }, { name: "Venezuela", flag: "🇻🇪" },
  { name: "Vietname", flag: "🇻🇳" }, { name: "Zâmbia", flag: "🇿🇲" }, { name: "Zimbabué", flag: "🇿🇼" }
];